#pragma config(Sensor, S1,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorA,          Motor1,        tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	float Kp = 13; // Proportional gain
	float Ki = 0.011; // Integral gain
	float Kd = 2; // Derivative gain
	float TargetAngle = 71;  //Target Angle


	float error = 0;
	float lastError = 0;
	float integral = 0;
	float derivative = 0;
	float correction = 0;

	//startup
	setLEDColor(ledRedFlash);
	wait(2);
	setLEDColor(ledRed);
	resetGyro(Gyro);
	wait(1);
	getGyroDegrees(Gyro);
	playSound(soundBeepBeep);
	setLEDColor(ledGreen);
	waitForButtonPress(); // wait
	playSound(soundFastUpwardTones);
	setLEDColor(ledGreenFlash);


	while(1){

		// Calculate the error
		error = TargetAngle - getGyroDegrees(Gyro);

		// Calculate integral
		integral += error;

		// Calculate derivative
		derivative =  (error - lastError);


		// Calculate correction
		correction = (Kp * error) + (Ki * integral) + (Kd * derivative);


		// Safety check
		if (abs(error) > 35) {
			motor[Motor1] = 0;
			playSound(soundDownwardTones);
			wait10Msec(100);
			break; // Stop the loop if correction is too high
		}


		// Apply correction to motors
		motor[Motor1] = correction;

		// Remember the error for the next loop iteration
		lastError = error;

	}
}
